# Form implementation generated from reading ui file 'option.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_option_window(object):
    def setupUi(self, option_window):
        option_window.setObjectName("option_window")
        option_window.resize(299, 201)
        option_window.setMinimumSize(QtCore.QSize(299, 201))
        option_window.setMaximumSize(QtCore.QSize(299, 201))
        self.centralwidget = QtWidgets.QWidget(parent=option_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_success_option = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_success_option.setGeometry(QtCore.QRect(10, 20, 261, 21))
        self.label_success_option.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_success_option.setObjectName("label_success_option")
        self.radioButton_checking_option = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_checking_option.setGeometry(QtCore.QRect(20, 70, 82, 17))
        self.radioButton_checking_option.setObjectName("radioButton_checking_option")
        self.radioButton_savings_option = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_savings_option.setGeometry(QtCore.QRect(180, 70, 82, 17))
        self.radioButton_savings_option.setObjectName("radioButton_savings_option")
        self.pushButton_option = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_option.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.pushButton_option.setObjectName("pushButton_option")
        option_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=option_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 299, 21))
        self.menubar.setObjectName("menubar")
        option_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=option_window)
        self.statusbar.setObjectName("statusbar")
        option_window.setStatusBar(self.statusbar)

        self.retranslateUi(option_window)
        QtCore.QMetaObject.connectSlotsByName(option_window)

    def retranslateUi(self, option_window):
        _translate = QtCore.QCoreApplication.translate
        option_window.setWindowTitle(_translate("option_window", "MainWindow"))
        self.label_success_option.setText(_translate("option_window", "Success! Which account would you like to access?"))
        self.radioButton_checking_option.setText(_translate("option_window", "Checking"))
        self.radioButton_savings_option.setText(_translate("option_window", "Savings"))
        self.pushButton_option.setText(_translate("option_window", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    option_window = QtWidgets.QMainWindow()
    ui = Ui_option_window()
    ui.setupUi(option_window)
    option_window.show()
    sys.exit(app.exec())
